backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

local_backend: true

collections:
  # 1) Jedan JSON fajl sa tekstovima i kontaktom
  - name: "sadrzaj"
    label: "Sadržaj sajta"
    files:
      - label: "Tekstovi — O nama i kontakt"
        name: "tekstovi"
        file: "index_copy.json"
        format: "json"
        fields:
          - { label: "O nama (tekst)", name: "o_nama", widget: "text", default: "Višegodišnje iskustvo i repertoar, profesionalna oprema i zagarantovan vrhunski provod je ono što možete očekivati od nas." }
          - { label: "Kontakt e-mail", name: "email", widget: "string", default: "QuantoCostaBand@gmail.com" }
          - { label: "Telefon", name: "telefon", widget: "string", default: "+381 66 557 1907" }
          - { label: "Instagram URL", name: "instagram", widget: "string", default: "https://www.instagram.com/quantocostaband" }

  # 2) Jedan JSON fajl sa listom datuma (stringovi YYYY-MM-DD)
  - name: "kalendar"
    label: "Kalendar — rezervacije"
    files:
      - label: "Rezervisani datumi"
        name: "bookovani"
        file: "data/booked.json"
        format: "json"
        fields:
          - label: "Rezervisani datumi"
            name: "booked"
            widget: "list"
            field:
              label: "Datum"
              name: "date"
              widget: "date"
              format: "YYYY-MM-DD"

  # 3) Galerija kao folder kolekcija (svaka slika novi zapis)
  - name: "galerija"
    label: "Galerija slika"
    folder: "assets/gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "webp"
    fields:
      - { label: "Slika", name: "image", widget: "image" }
      - { label: "Alt tekst", name: "alt", widget: "string", required: false }

  # 4) Video kao folder kolekcija
  - name: "video"
    label: "Video"
    folder: "assets/video"
    create: true
    slug: "{{slug}}"
    extension: "mp4"
    fields:
      - { label: "Video (MP4)", name: "file", widget: "file" }
      - { label: "Poster slika (jpg/webp)", name: "poster", widget: "image", required: false }

