backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"


local_backend: true

collections:
  # 1) Glavni tekstovi sajta iz index_copy.json
  - name: "sadrzaj"
    label: "Sadržaj sajta"
    file: "index_copy.json"
    format: "json"
    fields:
      - { label: "O nama (tekst)", name: "o_nama", widget: "text", default: "Višegodišnje iskustvo i repertoar, profesionalna oprema i zagarantovan vrhunski provod je ono što možete očekivati od nas." }
      - { label: "Kontakt e-mail", name: "email", widget: "string", default: "QuantoCostaBand@gmail.com" }
      - { label: "Telefon", name: "telefon", widget: "string", default: "+381 66 557 1907" }
      - { label: "Instagram URL", name: "instagram", widget: "string", default: "https://www.instagram.com/quantocostaband" }

  # 2) Kalendar rezervacija (lista datuma) iz data/booked.json
  - name: "kalendar"
    label: "Kalendar — rezervacije"
    file: "data/booked.json"
    format: "json"
    fields:
      - label: "Rezervisani datumi"
        name: "booked"
        widget: "list"
        fields:
          - { label: "Datum", name: "datum", widget: "date", format: "YYYY-MM-DD" }

  # 3) Galerija slika (svaki unos je .webp u assets/gallery)
  - name: "galerija"
    label: "Galerija slika"
    folder: "assets/gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "webp"
    fields:
      - { label: "Slika", name: "image", widget: "image" }
      - { label: "Alt tekst", name: "alt", widget: "string", required: false }

  # 4) Video fajlovi (MP4) u assets/video
  - name: "video"
    label: "Video (MP4)"
    folder: "assets/video"
    create: true
    slug: "{{slug}}"
    extension: "mp4"
    fields:
      - { label: "Video fajl (MP4)", name: "file", widget: "file" }
      - { label: "Poster (slika)", name: "poster", widget: "image", required: false }

